### PR TITLE
Add in initial support for swiping

### PR DESCRIPTION
**Pull request by CalebJohn**

### CODE REVIEW

**Comment by CalebJohn** [comment]
This adds in support for swiping up and down while playing the game, we still need to figure out how to move regular touches into the touchpressed to make them more responsive.

**Comment by 8bitgentleman** [comment]
Sorry it's been so long since you opened this.  I finally got around to testing it and there are a few bugs with the swipes.  
- Up seems to be constantly being passed.  If I stand still the character will look upwards and if I enter a 2.5D space the character will continuously walk up.
- I had trouble getting the character to crouch or crawl.  The swipe was definitely being passed but the character didn't respond.  This is most likely due to the previous but.

Other than that this looks pretty great!

**Comment by CalebJohn** [comment]
This should finally be working, sorry for the delay.

**Comment by 8bitgentleman** [comment]
+1 Looks good!

**Pull request merged**
