### PR TITLE
Target trouser beam at player

### PR DESCRIPTION
**Pull request by CalebJohn**
There is still a little more that can be fixed here, I'll try to get back to this after attempting that tavern fix.

### CODE REVIEW

**Comment by 8bitgentleman** [comment]
This looks great, do you think I should tilt the sprite?

**Comment by CalebJohn** [comment]
Initially I thought you would have to but after looking at it this seems fine, although it wouldn't hurt to try it and see how we like it, I can write that up tomorrow if you'd like.

**Comment by 8bitgentleman** [comment]
What about instead of physically changing the sprite we rotate it when it's drawn according to the angle that it's thrown at.  So when the projectile is drawn in projectile.lua set the rotation to a variable that is changed when the angle is determined at the start of the throw.  Also what's the weird offset issue when the snake throws a beam while facing right?

**Comment by CalebJohn** [comment]
I agree in code would be better, I don't think it will rotate enough for there to be bounding issues but I I'll write it up today and we can take a look and see how it is.

Usually the offset issue has to do with the size of the enemy sprite and the size of the projectile, I think there are some variables that should be able to adjust this, if not we can probably fix this another way.

**Comment by CalebJohn** [comment]
@8bitgentleman I screwed up this branch I'm going to abort it

**Pull request closed without merging**
